# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=256)),
                ('model', models.CharField(default='', max_length=256)),
                ('user', models.CharField(default='', max_length=20)),
                ('number', models.CharField(default='', max_length=16)),
                ('vin_code', models.CharField(default='', max_length=20)),
                ('color_text', models.CharField(blank=True, default='', max_length=64)),
                ('color_code', models.CharField(blank=True, default='', max_length=16)),
                ('year', models.CharField(blank=True, default='', max_length=5)),
                ('passport_number', models.CharField(blank=True, default='', max_length=64)),
                ('engine_capacity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('info', models.TextField()),
                ('is_paid', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Reregestration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(blank=True, default='', max_length=20)),
                ('buyer', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_text', models.CharField(blank=True, max_length=256)),
                ('seller_sign', models.TextField(blank=True)),
                ('buyer_sign', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_tax_paid', models.BooleanField(default=False)),
                ('inspection_time', models.CharField(blank=True, default='', max_length=20)),
                ('is_inspection_success', models.BooleanField(default=False)),
                ('is_number_received', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('info', models.TextField()),
                ('is_paid', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
            options={
                'verbose_name_plural': 'taxes',
            },
        ),
    ]
