# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reregestration',
            name='inspection_time',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
