# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reregestration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default='', max_length=20)),
                ('buyer', models.CharField(default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_text', models.CharField(max_length=256)),
                ('seller_sign', models.TextField()),
                ('buyer_sign', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_tax_paid', models.BooleanField(default=False)),
                ('inspection_time', models.CharField(default='', max_length=20)),
                ('is_inspection_success', models.BooleanField(default=False)),
                ('is_number_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='car',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='seller',
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.AddField(
            model_name='reregestration',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
    ]
