# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20170602_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color_text',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='amount_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='buyer_sign',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='inspection_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reregestration',
            name='seller_sign',
            field=models.TextField(blank=True),
        ),
    ]
