# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20170607_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reregestration',
            name='inspection_time',
        ),
        migrations.RemoveField(
            model_name='reregestration',
            name='is_inspection_success',
        ),
    ]
