# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20170613_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='reregistration',
            name='number',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
