# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20170704_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_html', models.TextField()),
                ('template_pdf', models.TextField()),
                ('template_xml', models.TextField()),
                ('style', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='reregistration',
            name='agreement_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reregistration',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Agreement'),
        ),
    ]
