# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20170704_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='owner',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
