# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20170712_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementtemplate',
            name='owner',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
