# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20170712_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='display_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
