# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_remove_reregistration_agreement_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('car_vin_code', models.CharField(max_length=20)),
                ('is_substitutive', models.BooleanField()),
                ('substitutive_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('result', models.TextField()),
                ('is_result_success', models.BooleanField(default=False)),
            ],
        ),
    ]
