# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_remove_reregistration_agreement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5),
        ),
    ]
