# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_substitutive',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='substitutive_info',
        ),
        migrations.AddField(
            model_name='registration',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
