# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20170822_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='number',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
