# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20170824_0721'),
        ('cars', '0022_auto_20170824_0550'),
    ]

    operations = [
    ]
