# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_merge_20170824_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
        ),
    ]
