# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 08:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('session', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('user', models.CharField(max_length=256)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
