# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.CharField(max_length=3)),
                ('characters', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=2)),
                ('is_sold', models.BooleanField(default=False)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
