# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
