# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numberplates', '0002_auto_20170606_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberplate',
            options={'ordering': ['digits']},
        ),
    ]
