# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplates', '0004_numberplate_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
