# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20170609_0502'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='reregestration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Reregestration'),
        ),
    ]
