# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_inspection_reregestration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.Inspector'),
        ),
    ]
