# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_deregistration'),
        ('controller', '0005_auto_20170613_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='deregistration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Deregistration'),
        ),
    ]
