# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_inspection_deregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspector',
        ),
        migrations.AddField(
            model_name='inspection',
            name='allower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allower', to='controller.Inspector'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_prelimenary_success',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_revision_success',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='inspection',
            name='prelimenary_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='revision_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='revisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to='controller.Inspector'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='role',
            field=models.CharField(choices=[('rev', 'revisor'), ('all', 'allower'), ('adm', 'administrator')], default='rev', max_length=3),
        ),
    ]
