# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_merge_20170824_0937'),
        ('controller', '0008_auto_20170728_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='registration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Registration'),
        ),
    ]
