# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_inspection_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
