# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_inspection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='time',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
